type User {
  email: String! @unique
  profile: Profile!
  owns: [Community] @relation(name: "community_owner")
  memberOf: [Community] @relation(name: "community_member")
  discordTokens: Token!
}

type Profile @embedded {
  firstName: String!
  lastName: String!
  username: String!
  avatar: String!
  locale: String!
  country: String!
  dob: Date!
}

type Token @embedded {
  access_token: String!
  expires_in: Int!
  refresh_token: String!
  scope: String!
  token_type: String!
}

type Community {
  name: String!
  tag: String!
  country: String!
  locale: String!
  iconUrl: String!
  owner: User! @relation(name: "community_owner")
  members: [User]! @relation(name: "community_member")
}
